Support mise and update tools

diff --git a/bin/env/clojure-setup b/bin/env/clojure-setup
--- a/bin/env/clojure-setup
+++ b/bin/env/clojure-setup
@@ -2,10 +2,26 @@
 set -euo pipefail
 
 PROJECT_DIR="$(cd -- "$(dirname "${BASH_SOURCE}")" ; cd ../.. > /dev/null 2>&1 && pwd -P)"
-ASDF_PLUGIN=clojure
-ASDF_PLUGIN_URL=https://github.com/asdf-community/asdf-clojure.git
 
-source $PROJECT_DIR/bin/env/asdf-helper.bash
-asdf-update-plugin
+source $PROJECT_DIR/bin/env/select-tool-versions-manager
+
+case "$TOOL_VERSIONS_MANAGER" in
+  asdf|asdf-vm)
+    echo "Setting up clojure via asdf"
+    ASDF_PLUGIN=clojure
+    ASDF_PLUGIN_URL=https://github.com/asdf-community/asdf-clojure.git
+    source $PROJECT_DIR/bin/env/asdf-helper.bash
+    asdf-update-plugin
+    asdf install clojure
+    ;;
+  mise)
+    echo "Setting up clojure via mise"
+    mise install clojure
+    ;;
+  *)
+    echo "ERROR: Unsupported TOOL_VERSIONS_MANAGER: $TOOL_VERSIONS_MANAGER"
+    exit 1
+    ;;
+esac
 
 # vi: ft=sh
diff --git a/bin/env/java-setup b/bin/env/java-setup
--- a/bin/env/java-setup
+++ b/bin/env/java-setup
@@ -1,11 +1,26 @@
 #!/usr/bin/env bash
 set -euo pipefail
-
 PROJECT_DIR="$(cd -- "$(dirname "${BASH_SOURCE}")" ; cd ../.. > /dev/null 2>&1 && pwd -P)"
-ASDF_PLUGIN=java
-ASDF_PLUGIN_URL=https://github.com/halcyon/asdf-java.git
 
-source $PROJECT_DIR/bin/env/asdf-helper.bash
-asdf-update-plugin
+source $PROJECT_DIR/bin/env/select-tool-versions-manager
+
+case "$TOOL_VERSIONS_MANAGER" in
+  asdf|asdf-vm)
+    echo "Setting up java via asdf"
+    ASDF_PLUGIN=java
+    ASDF_PLUGIN_URL=https://github.com/halcyon/asdf-java.git
+    source $PROJECT_DIR/bin/env/asdf-helper.bash
+    asdf-update-plugin
+    asdf install java
+    ;;
+  mise)
+    echo "Setting up java via mise"
+    mise install java
+    ;;
+  *)
+    echo "ERROR: Unsupported TOOL_VERSIONS_MANAGER: $TOOL_VERSIONS_MANAGER"
+    exit 1
+    ;;
+esac
 
 # vi: ft=sh
